version: '3.8'
services:
  blog_be_nginx:
    container_name: blog_be_nginx
    image: blog_be/nginx
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    ports:
      - "${APP_PORT:-80}:80"
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - blog_be_app
    networks:
      - blog_be

  blog_be_app:
    image: blog_be/app
    container_name: blog_be_app
    build:
      context: .
      dockerfile: ./.docker/php-fpm/Dockerfile
    volumes:
      - ./:/var/www/html
    depends_on:
      - blog_be_redis
    networks:
      - blog_be
    environment:
      # Database connection sẽ sử dụng RDS endpoint
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT:-5432}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

  blog_be_worker:
    container_name: blog_be_worker
    image: blog_be/worker
    build:
      context: .
      dockerfile: ./.docker/worker/Dockerfile
    volumes:
      - ./:/var/www/html
    depends_on:
      - blog_be_redis
    networks:
      - blog_be
    environment:
      # Database connection sẽ sử dụng RDS endpoint
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT:-5432}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

  # Xóa blog_be_pgsql service vì sử dụng RDS

  blog_be_redis:
    container_name: blog_be_redis
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - blog_be_redis:/data
    networks:
      - blog_be
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s

  # Adminer vẫn có thể sử dụng để connect tới RDS
  blog_be_adminer:
    container_name: blog_be_adminer
    image: adminer:latest
    ports:
      - '${FORWARD_ADMINER_PORT:-8089}:8080'
    networks:
      - blog_be

networks:
  blog_be:
    driver: bridge

volumes:
  # Xóa blog_be_postgres volume vì không cần thiết
  blog_be_redis:
    driver: local