version: '3.8'
services:
  blog_be_nginx:
    container_name: blog_be_nginx
    image: blog_be/nginx
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    ports:
      - "${APP_PORT:-80}:80"
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - blog_be_app
    networks:
      - blog_be

  blog_be_app:
    image: blog_be/app
    container_name: blog_be_app
    build:
      context: .
      dockerfile: ./.docker/php-fpm/Dockerfile
    volumes:
      - ./:/var/www/html
    depends_on:
      - blog_be_pgsql
      - blog_be_redis
    networks:
      - blog_be

  blog_be_worker:
    container_name: blog_be_worker
    image: blog_be/worker
    build:
      context: .
      dockerfile: ./.docker/worker/Dockerfile
    volumes:
      - ./:/var/www/html
    depends_on:
      - blog_be_pgsql
      - blog_be_redis
    networks:
      - blog_be

  blog_be_pgsql:
    container_name: blog_be_pgsql
    image: 'postgres:15'
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - blog_be_postgres:/var/lib/postgresql/data
    networks:
      - blog_be
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '-q'
        - '-d'
        - '${DB_DATABASE}'
        - '-U'
        - '${DB_USERNAME}'
      retries: 3
      timeout: 5s

  blog_be_redis:
    container_name: blog_be_redis
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - blog_be_redis:/data
    networks:
      - blog_be
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s

  blog_be_adminer:
    container_name: blog_be_adminer
    image: adminer:latest
    ports:
      - '${FORWARD_ADMINER_PORT:-8089}:8080'
    depends_on:
      - blog_be_pgsql
    networks:
      - blog_be

networks:
  blog_be:
    driver: bridge

volumes:
  blog_be_postgres:
    driver: local
  blog_be_redis:
    driver: local
